<a href="https://colab.research.google.com/github/antoniojoelson/ChatbotTelegram/blob/main/Sistema_Linear.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lista de exercicios 
##01

In [5]:
import numpy as np

In [4]:


A = np.array([[2,-1],[1,5]])
B = np.array([7,-2])
D = np.linalg.det(A)
Ax = np.array([[7,-1],[-2,5]])
Dx = np.linalg.det(Ax)
print(Dx)
print(D)

result = np.linalg.solve(A,B)

detA  = np.linalg.det(A)
detAx = np.linalg.det(Ax)


if detA !=0:
    S = np.linalg.solve(A,B)
    print('SPD',S)
elif detA == 0 and detAx == 0:
    print ('SPI')
else:
    print('SI')

33.0
11.000000000000002
SPD [ 3. -1.]


##02

In [6]:
A = np.array([[1,2,-1],[3,-4,5],[1,1,9]]) # matriz dos coeficientes
print(A)
B = np.array([0,10,1])         # termos independentes
Ax = np.array([[0,2,-1],[10,-4,5],[1,1,9]])   # troca coluna x pelo termo independente
detA = np.linalg.det(A)
detAx = np.linalg.det(Ax)

# Analisar os determinantes

if detA !=0:
  S = np.linalg.solve(A,B)
  print("SPD")
  print(S)
else:
  if detA ==0 and detAx ==0:
    print("SPI")
  else:
    print("SI")



[[ 1  2 -1]
 [ 3 -4  5]
 [ 1  1  9]]
SPD
[ 2.00000000e+00 -1.00000000e+00  4.82705663e-17]


#03

In [7]:
A = np.array([[1,2],[2,3]])
B = np.array([5,-4])
D = np.linalg.det(A)
Ax = np.array([[5,2],[-4,3]])
Dx = np.linalg.det(Ax)
print(Dx)
print(D)

result = np.linalg.solve(A,B)

detA  = np.linalg.det(A)
detAx = np.linalg.det(Ax)


if detA !=0:
    S = np.linalg.solve(A,B)
    print('SPD',S)
elif detA == 0 and detAx == 0:
    print ('SPI')
else:
    print('SI')

23.0
-1.0
SPD [-23.  14.]


#04

In [ ]:
A = np.array([[2,-1],[1,5]])
B = np.array([7,-2])
D = np.linalg.det(A)
Ax = np.array([[7,-1],[-2,5]])
Dx = np.linalg.det(Ax)
print(Dx)
print(D)

result = np.linalg.solve(A,B)

detA  = np.linalg.det(A)
detAx = np.linalg.det(Ax)


if detA !=0:
    S = np.linalg.solve(A,B)
    print('SPD',S)
elif detA == 0 and detAx == 0:
    print ('SPI')
else:
    print('SI')

33.0
11.000000000000002
SPD [ 3. -1.]


##05

In [8]:
A = np.array([[2,-1,1],[1,-1,2],[1,1,1]]) # matriz dos coeficientes
print(A)
B = np.array([3,3,6])         # termos independentes
Ax = np.array([[3,-1,1],[3,-1,2],[6,1,1]])   # troca coluna x pelo termo independente
detA = np.linalg.det(A)
detAx = np.linalg.det(Ax)

# Analisar os determinantes

if detA !=0:
  S = np.linalg.solve(A,B)
  print("SPD")
  print(S)
else:
  if detA ==0 and detAx ==0:
    print("SPI")
  else:
    print("SI")



[[ 2 -1  1]
 [ 1 -1  2]
 [ 1  1  1]]
SPD
[1.8 2.4 1.8]


#06

In [9]:
A = np.array([[1,4,7],[2,3,6],[5,1,-1]]) # matriz dos coeficientes
print(A)
B = np.array([2,2,8])         # termos independentes
Ax = np.array([[2,4,7],[2,3,6],[8,1,-1]])   # troca coluna x pelo termo independente
detA = np.linalg.det(A)
detAx = np.linalg.det(Ax)

# Analisar os determinantes

if detA !=0:
  S = np.linalg.solve(A,B)
  print("SPD")
  print(S)
else:
  if detA ==0 and detAx ==0:
    print("SPI")
  else:
    print("SI")



[[ 1  4  7]
 [ 2  3  6]
 [ 5  1 -1]]
SPD
[ 1.  2. -1.]
